//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string TechnicalDescription { get; set; }
        public Nullable<int> AnalysisDocumentId { get; set; }
    
        public virtual Main Main { get; set; }
    }
}
