//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Main
    {
        public Main()
        {
            this.Counters = new HashSet<Counter>();
            this.Donations = new HashSet<Donation>();
            this.Infoes = new HashSet<Info>();
            this.LikesCounters = new HashSet<LikesCounter>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> LikeCounterId { get; set; }
        public Nullable<int> LikesRequiredTotal { get; set; }
        public Nullable<int> DonationsId { get; set; }
        public Nullable<decimal> DonationsRequiredTotal { get; set; }
        public Nullable<int> IconId { get; set; }
    
        public virtual ProjectState ProjectState { get; set; }
        public virtual ICollection<Counter> Counters { get; set; }
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual ICollection<Info> Infoes { get; set; }
        public virtual ICollection<LikesCounter> LikesCounters { get; set; }
    }
}
