//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftwareDreamEntities : DbContext
    {
        public SoftwareDreamEntities()
            : base("name=SoftwareDreamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CredentialsType> CredentialsTypes { get; set; }
        public virtual DbSet<ProjectState> ProjectStates { get; set; }
        public virtual DbSet<Counter> Counters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Facebook> Facebooks { get; set; }
        public virtual DbSet<GPlu> GPlus { get; set; }
        public virtual DbSet<LinkedIn> LinkedIns { get; set; }
        public virtual DbSet<Local> Locals { get; set; }
        public virtual DbSet<Twitter> Twitters { get; set; }
        public virtual DbSet<Donation> Donations { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<LikesCounter> LikesCounters { get; set; }
        public virtual DbSet<Main> Mains { get; set; }
    }
}
