//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectState
    {
        public ProjectState()
        {
            this.Mains = new HashSet<Main>();
        }
    
        public int Id { get; set; }
        public string ProjectStateName { get; set; }
    
        public virtual ICollection<Main> Mains { get; set; }
    }
}
