//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Counters = new HashSet<Counter>();
            this.Donations = new HashSet<Donation>();
            this.Facebooks = new HashSet<Facebook>();
            this.GPlus = new HashSet<GPlu>();
            this.LinkedIns = new HashSet<LinkedIn>();
            this.Locals = new HashSet<Local>();
            this.Twitters = new HashSet<Twitter>();
        }
    
        public int Id { get; set; }
        public Nullable<short> CredentialsTypeId { get; set; }
    
        public virtual CredentialsType CredentialsType { get; set; }
        public virtual ICollection<Counter> Counters { get; set; }
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual ICollection<Facebook> Facebooks { get; set; }
        public virtual ICollection<GPlu> GPlus { get; set; }
        public virtual ICollection<LinkedIn> LinkedIns { get; set; }
        public virtual ICollection<Local> Locals { get; set; }
        public virtual ICollection<Twitter> Twitters { get; set; }
    }
}
